---
title: "unusedcode"
author: "Catherine Sheen"
date: "25/05/2021"
output: html_document
---

```{r}
library(here)

library(tidyverse)

library(forcats)

library(fBasics)

library(reshape2)

library(rsconnect)

library(shiny)
```



```{r}

#melt the data into long form 
long <- melt(df, measure.vars = c("iasrs", "hasrs"))

#predetermining the graph presets 
#Innatentive ADHD traits
themeadj = theme_light(base_size = 20) + theme(legend.background = element_rect(fill = "transparent", colour =))

headingadj = theme(plot.caption = element_text(hjust = 0)) +
  theme(plot.title = element_text(hjust = 0.5))


adhdscale = scale_x_continuous(name="ADHD trait score" 
) 



cesdscale =  scale_y_continuous(name="Depression symptom score"
)

ders_gradient = scale_colour_gradient(low = "midnightblue", 
                                      high = "cyan1")





legend =  guides(size = guide_legend(reverse = TRUE, order = 2),
                 color = guide_colourbar(order = 1),
                 shape = guide_legend(order = 3),
                 linetype = guide_legend(order = 4))


shapelabels = scale_shape_discrete(labels = c("Innatentive", "Hyperactive"))
linelabels = scale_linetype_discrete(labels = c("Innatentive", "Hyperactive"))   

#non-acceptance  
nonacceptplot <- ggplot(long, aes(value, cesd, shape = variable)) + 
  ders_gradient + cesdscale  +  adhdscale + 
  geom_smooth(method = "lm", se = F, color = "midnightblue", aes(linetype = variable)) +
  geom_point(aes(size = nonaccept, color = nonaccept)) + 
  themeadj + headingadj  + legend + shapelabels + linelabels +
  ggtitle("Depression scores per ADHD traits and non-acceptance regulation difficulties") + 
  labs(color = "Non-acceptance score", shape = "ADHD type", linetype = "ADHD  type", size = "Non-acceptance score") +
  guides(shape = guide_legend(override.aes = list(size = 5)), linetype = guide_legend(override.aes = list(size = 1))) 

#goals
goalsplot <- ggplot(long, aes(value, cesd, shape = variable)) + 
  ders_gradient + cesdscale  +  adhdscale + 
  geom_smooth(method = "lm", se = F, color = "midnightblue", aes(linetype = variable)) +
  geom_point(aes(size = goals, color = goals)) + 
  themeadj + headingadj  + legend + shapelabels + linelabels +
  ggtitle("Depression scores per ADHD traits and Goals regulation difficulties") + 
  labs(color = "Goals score", shape = "ADHD type", linetype = "ADHD  type", size = "Goals score") +
  guides(shape = guide_legend(override.aes = list(size = 5)), linetype = guide_legend(override.aes = list(size = 1))) 

goalsplot

#impulse 
impulseplot <- ggplot(long, aes(value, cesd, shape = variable)) + 
  ders_gradient + cesdscale  +  adhdscale + 
  geom_smooth(method = "lm", se = F, color = "midnightblue", aes(linetype = variable)) +
  geom_point(aes(size = impulse, color = impulse)) + 
  themeadj + headingadj  + legend + shapelabels + linelabels +
  ggtitle("Depression scores per ADHD traits and Impulse regulation difficulties") + 
  labs(color = "Impulse score", shape = "ADHD type", linetype = "ADHD  type", size = "Impulse score") +
  guides(shape = guide_legend(override.aes = list(size = 5)), linetype = guide_legend(override.aes = list(size = 1)))

impulseplot

#awareness 

awarenessplot <- ggplot(long, aes(value, cesd, shape = variable)) + 
  ders_gradient + cesdscale  +  adhdscale + 
  geom_smooth(method = "lm", se = F, color = "midnightblue", aes(linetype = variable)) +
  geom_point(aes(size = awareness, color = awareness)) + 
  themeadj + headingadj  + legend + shapelabels + linelabels +
  ggtitle("Depression scores per ADHD traits and Awareness regulation difficulties") + 
  labs(color = "Awareness score", shape = "ADHD type", linetype = "ADHD  type", size = "Awareness score") +
  guides(shape = guide_legend(override.aes = list(size = 5)), linetype = guide_legend(override.aes = list(size = 1)))

awarenessplot

#strategies 
strategiesplot <- ggplot(long, aes(value, cesd, shape = variable)) + 
  ders_gradient + cesdscale  +  adhdscale + 
  geom_smooth(method = "lm", se = F, color = "midnightblue", aes(linetype = variable)) +
  geom_point(aes(size = strategies, color = strategies)) + 
  themeadj + headingadj  + legend + shapelabels + linelabels +
  ggtitle("Depression scores per ADHD traits and Strategies regulation difficulties") + 
  labs(color = "Strategies score", shape = "ADHD type", linetype = "ADHD  type", size = "Strategies score") +
  guides(shape = guide_legend(override.aes = list(size = 5)), linetype = guide_legend(override.aes = list(size = 1)))

strategiesplot   

#clarity
clarityplot <- ggplot(long, aes(value, cesd, shape = variable)) + 
  ders_gradient + cesdscale  +  adhdscale + 
  geom_smooth(method = "lm", se = F, color = "midnightblue", aes(linetype = variable)) +
  geom_point(aes(size = clarity, color = clarity)) + 
  themeadj + headingadj  + legend + shapelabels + linelabels +
  ggtitle("Depression scores per ADHD traits and Clarity regulation difficulties") + 
  labs(color = "Clarity score", shape = "ADHD type", linetype = "ADHD  type", size = "Clarity score") +
  guides(shape = guide_legend(override.aes = list(size = 5)), linetype = guide_legend(override.aes = list(size = 1)))

clarityplot
```

cont. 
```{r}


#basic visualisations of the data 
p <- ggplot(df, aes(asrs, cesd)) 
p +  geom_point(size = 6, alpha = .5) + geom_smooth(method = "lm", se = F) 

p <- ggplot(df, aes(asrs, ders)) 
p  +   geom_point(color = "green", size = 10) + geom_smooth(method = "lm", se = F) 

p <- ggplot(df, aes(cesd, ders))  
  p  +   geom_point(size = 7) + geom_smooth(method = "lm", se = F) 
  
#visualisations with innatentive and hyperactive type 
  
  hcesd <- ggplot(df, aes(hasrs, cesd)) 
  hcesd +  geom_point(size = 6, alpha = .5) + geom_smooth(se = F) 
  
  icesd <- ggplot(df, aes(iasrs, cesd)) 
  icesd +  geom_point(size = 6, alpha = .5) + geom_smooth(se = F) 

  iders <- ggplot(df, aes(iasrs, ders)) 
  iders +  geom_point(size = 6, alpha = .5) + geom_smooth(method = "lm", se = F) 
  
  hders <- ggplot(df, aes(hasrs, ders)) 
  hders +  geom_point(size = 6, alpha = .5) + geom_smooth(method = "lm", se = F) 
  
#swapping x and y axis 
  p <- ggplot(df, aes(cesd, asrs)) 
  p +  geom_point(size = 10, alpha = 0.9) + geom_smooth(method = "lm", se = F) 

#graph with asrsXcesd with ders represented as colour 
  p <- ggplot(df, aes(asrs, cesd, colour = ders, fill = ders)) 
  p +  geom_point(size = 10, alpha = 0.9) + geom_smooth(method = "lm", se = F)
  
  p <- ggplot(df, aes(asrs, cesd,)) 
  p +  geom_point(mapping = aes(colour = ders, size = ders)) + geom_smooth(method = "lm", se = F)

#graph looks better with a xlog10 however this results in a uneven scale and potentially biases the impression perceived  
#changing how much axis increases by 
  ders =  scale_colour_gradient(low = "cyan", high = "magenta")
  
  p <- ggplot(df, aes(asrs, cesd,)) 
  p +  geom_point(mapping = aes(size = ders, color = ders)) +
       geom_smooth(method = "lm", se = F) +
        scale_x_continuous(name="ADHD trait score") + 
          scale_y_continuous(name="Depression symptom score") + 
            scale_color_gradient(low = "purple4", high = "magenta")
           
  
#graph per ders construct 
  nonacceptplot <- ggplot(df, aes(asrs, cesd,)) 
  nonacceptplot +  geom_point(mapping = aes(colour = nonaccept, size = nonaccept)) + geom_smooth(method = "lm", se = F)
 
  goalsplot <- ggplot(df, aes(asrs, cesd,)) 
  goalsplot +  geom_point(mapping = aes(colour = goals, size = goals)) + geom_smooth(method = "lm", se = F)  

  impulseplot <- ggplot(df, aes(asrs, cesd,)) 
  impulseplot +  geom_point(mapping = aes(colour = impulse, size = impulse)) + geom_smooth(method = "lm", se = F)
  
  awarenessplot <- ggplot(df, aes(asrs, cesd,)) 
  awarenessplot +  geom_point(mapping = aes(colour = awareness, size = awareness)) + geom_smooth(method = "lm", se = F)

  strategiesplot <- ggplot(df, aes(asrs, cesd,)) 
  strategiesplot +  geom_point(mapping = aes(colour = strategies, size = strategies)) + geom_smooth(method = "lm", se = F)  
  
  clarityplot <- ggplot(df, aes(asrs, cesd,)) 
  clarityplot +  geom_point(mapping = aes(colour = clarity, size = clarity)) + geom_smooth(method = "lm", se = F) 

#ders construct X adhd type 
  
  #inattentive
  inonacceptplot <- ggplot(df, aes(iasrs, cesd,)) 
  inonacceptplot +  geom_point(mapping = aes(colour = nonaccept, size = nonaccept)) + geom_smooth(method = "lm", se = F)
  
  igoalsplot <- ggplot(df, aes(iasrs, cesd,)) 
  igoalsplot +  geom_point(mapping = aes(colour = goals, size = goals)) + geom_smooth(method = "lm", se = F)  
  
  iimpulseplot <- ggplot(df, aes(iasrs, cesd,)) 
  iimpulseplot +  geom_point(mapping = aes(colour = impulse, size = impulse)) + geom_smooth(method = "lm", se = F)
  
  iawarenessplot <- ggplot(df, aes(iasrs, cesd,)) 
  iawarenessplot +  geom_point(mapping = aes(colour = awareness, size = awareness)) + geom_smooth(method = "lm", se = F)
  
  istrategiesplot <- ggplot(df, aes(iasrs, cesd,)) 
  istrategiesplot +  geom_point(mapping = aes(colour = strategies, size = strategies)) + geom_smooth(method = "lm", se = F)  
  
  iclarityplot <- ggplot(df, aes(iasrs, cesd,)) 
  iclarityplot +  geom_point(mapping = aes(colour = clarity, size = clarity)) + geom_smooth(method = "lm", se = F) 
  
  #hyperactive 
  hnonacceptplot <- ggplot(df, aes(hasrs, cesd,)) 
  hnonacceptplot +  geom_point(mapping = aes(colour = nonaccept, size = nonaccept)) + geom_smooth(method = "lm", se = F)
  
  hgoalsplot <- ggplot(df, aes(hasrs, cesd,)) 
  hgoalsplot +  geom_point(mapping = aes(colour = goals, size = goals)) + geom_smooth(method = "lm", se = F)  
  
  himpulseplot <- ggplot(df, aes(hasrs, cesd,)) 
  himpulseplot +  geom_point(mapping = aes(colour = impulse, size = impulse)) + geom_smooth(method = "lm", se = F)
  
  hawarenessplot <- ggplot(df, aes(hasrs, cesd,)) 
  hawarenessplot +  geom_point(mapping = aes(colour = awareness, size = awareness)) + geom_smooth(method = "lm", se = F)
  
  hstrategiesplot <- ggplot(df, aes(hasrs, cesd,)) 
  hstrategiesplot +  geom_point(mapping = aes(colour = strategies, size = strategies)) + geom_smooth(method = "lm", se = F)  
  
  hclarityplot <- ggplot(df, aes(hasrs, cesd,)) 
  hclarityplot +  geom_point(mapping = aes(colour = clarity, size = clarity)) + geom_smooth(method = "lm", se = F) 

```

Column {.sidebar}
--------------------------------------------------
```{r, eval=FALSE}
df <- read.csv("shiny/dataframe.csv")

 fluidPage( 
    
  
    titlePanel("ADHD traits, Depression Symptoms and Emotion Regulation Domains"),
    
    sidebarPanel(
        
        selectInput('x', 'Reported Depression Symptoms', list("Depression Score" = "cesd")),
        selectInput('y', 'ADHD trait type', list(Innatentive = "iasrs", Hyperactive = "hasrs")),
        selectInput('ders', 'Emotion Regulation Difficulties per Domain', c(list("Non-Acceptance" = "nonaccept", Goals = "goals", Impulse = "impulse", Awareness = "awareness", Strategies = "strategies", Clarity = "clarity"))),
        #selectInput('size', 'Size', c(list("Non-Acceptance" = "nonaccept", Goals = "goals", Impulse = "impulse", Awareness = "awareness", Strategies = "strategies", Clarity = "clarity"))) #this line was unnecessary 
    
    ),
    
    mainPanel(
        plotOutput('plot')
    )
)

```

Column
--------------------------------------------------
```{r eval=FALSE}

 function(input, output) {
 output$plot <- renderPlot({
       
        p <- ggplot(df, aes_string(x=input$x, y=input$y)) + geom_point()
        
        (input$color)
            p <- p + aes_string(color=input$ders)
            
        (input$size)
            p <- p + aes_string(size=input$ders) + guides(size = guide_legend(reverse = TRUE))
        

        print(p)
        
    }, height=700) }
```

